theme: jekyll-theme-cayman
title: Stylianos Tsiaras
description: Welcome to my webpage. Here, you can find my job market paper, CV and other stuff about me
footer-links:
  dribbble:
  email: s.tsiaras@surrey.ac.uk
  facebook:
  flickr:
  github: st348
  instagram:
  linkedin:
  pinterest:
  twitter: 
  stackoverflow:
  youtube:
  googleplus: 
